"""add names

Revision ID: 0c5760cc9eb9
Revises: 013b02a19449
Create Date: 2025-02-15 17:34:43.100507

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "0c5760cc9eb9"
down_revision: Union[str, None] = "013b02a19449"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "projects",
        sa.Column("sender_name", sa.String(length=32), nullable=True),
    )
    op.add_column(
        "projects",
        sa.Column("recipient_name", sa.String(length=32), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("projects", "recipient_name")
    op.drop_column("projects", "sender_name")
    # ### end Alembic commands ###
