"""add teelgram_id for users table

Revision ID: 9ef4f37ff316
Revises: c73a119a7f03
Create Date: 2025-02-11 16:15:17.075295

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "9ef4f37ff316"
down_revision: Union[str, None] = "c73a119a7f03"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users", sa.Column("telegram_id", sa.Integer(), nullable=False)
    )
    op.create_unique_constraint(None, "users", ["telegram_id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "users", type_="unique")
    op.drop_column("users", "telegram_id")
    # ### end Alembic commands ###
