"""add owner_id

Revision ID: 2c9b03a71a7d
Revises: 9ef4f37ff316
Create Date: 2025-02-11 16:20:58.756879

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "2c9b03a71a7d"
down_revision: Union[str, None] = "9ef4f37ff316"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("chats", sa.Column("owner_id", sa.Integer(), nullable=False))
    op.create_foreign_key(
        None, "chats", "users", ["owner_id"], ["telegram_id"]
    )
    op.create_unique_constraint(None, "users", ["telegram_id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "users", type_="unique")
    op.drop_constraint(None, "chats", type_="foreignkey")
    op.drop_column("chats", "owner_id")
    # ### end Alembic commands ###
